services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - /home/oscar/Desktop/cloud_mount_volume:/var/lib/mysql

volumes:
  mysql-data: